#include <bits/stdc++.h>
#include <iostream>

#define ll long long

using std::cin;
using std::cout;
using std::endl;

int main() {
	cout << "What year was your house built?\n";
	int year;
	(cin >> year).get(); // discards the newline from the input queue
	cout << "What is its street address?\n";
	char address[80];
	cin.getline(address, 80);
	cout << "Year built: " << year << endl;
	cout << "Address: " << address << endl;
	cout << "Done!\n";

	return 0;
}

/* You never get the opportunity to enter address.
 * The problem is that when cin reads the year, it
 * leaves the newline generated by the Enter key in
 * the input queue. Then, cin.getline() reads that
 * newline as an empty line and assigns a null string
 * to the address array. The fix is to read and discard
 * the newline before reading the address. This can be
 * done several ways, including by using get()
 */

